# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7832b8f509b2cf18322fe48ab27e003fecdc23590501c912763a0032f55f2bfca2999a89674de32bdd7ef8e3c7dc5b18a4640f9b4cd52f347b2fe020dcc8623b

test:
  secret_key_base: 842986b04a2d048e41b3618c13326a1cd67cfa4176ea723b68b6d50429d089abdb7b79cec1c0fca8b49f19273ff770019f35892b8ab58c930bf97bfb0b5e68e7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
